In [1]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [2]:
import pandas as pd
df=pd.DataFrame({
    'color':['red','blue','green','white','black']
})
df

   color
0    red
1   blue
2  green
3  white
4  black

In [3]:
encoded=encoder.fit_transform(df[['color']]).toarray()
encoded

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [13]:
df_encoded=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
df_encoded

   color_black  color_blue  color_green  color_red  color_white
0          0.0         0.0          0.0        1.0          0.0
1          0.0         1.0          0.0        0.0          0.0
2          0.0         0.0          1.0        0.0          0.0
3          0.0         0.0          0.0        0.0          1.0
4          1.0         0.0          0.0        0.0          0.0

In [17]:
a=encoder.transform([['red']]).toarray()
df1=pd.DataFrame(a,columns=encoder.get_feature_names_out())
df1

/Users/barunwason/python/myenv/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   color_black  color_blue  color_green  color_red  color_white
0          0.0         0.0          0.0        1.0          0.0

In [21]:
pd.concat([df,df_encoded],axis=1)

   color  color_black  color_blue  color_green  color_red  color_white
0    red          0.0         0.0          0.0        1.0          0.0
1   blue          0.0         1.0          0.0        0.0          0.0
2  green          0.0         0.0          1.0        0.0          0.0
3  white          0.0         0.0          0.0        0.0          1.0
4  black          1.0         0.0          0.0        0.0          0.0

In [31]:
import seaborn as sns
data=sns.load_dataset('tips')
data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
b=encoder.fit_transform(data[['day']]).toarray()
df2=pd.DataFrame(b,columns=encoder.get_feature_names_out())
df2

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [35]:
pd.concat([data['day'],df2],axis=1).value_counts()

day   day_Fri  day_Sat  day_Sun  day_Thur
Sat   0.0      1.0      0.0      0.0         87
Sun   0.0      0.0      1.0      0.0         76
Thur  0.0      0.0      0.0      1.0         62
Fri   1.0      0.0      0.0      0.0         19
Name: count, dtype: int64

In [39]:
c=encoder.fit_transform(data[['sex']]).toarray()
df4=pd.DataFrame(c,columns=encoder.get_feature_names_out())
df4

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [40]:
pd.concat([data['sex'],df4],axis=1)

        sex  sex_Female  sex_Male
0    Female         1.0       0.0
1      Male         0.0       1.0
2      Male         0.0       1.0
3      Male         0.0       1.0
4    Female         1.0       0.0
..      ...         ...       ...
239    Male         0.0       1.0
240  Female         1.0       0.0
241    Male         0.0       1.0
242    Male         0.0       1.0
243  Female         1.0       0.0

[244 rows x 3 columns]