In [3]:
import pandas as pd

In [4]:
df1=pd.read_csv('/Users/barunwason/python/Python-NLP-Practice/NLP basics/Fake_News/News _dataset/Fake.csv')

In [5]:
df1['f/t']=0

In [6]:
df1

,title,text,subject,date,f/t
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [7]:
df2=pd.read_csv('/Users/barunwason/python/Python-NLP-Practice/NLP basics/Fake_News/News _dataset/True.csv')

In [8]:
df2['f/t']=1

In [9]:
df2

,title,text,subject,date,f/t
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [10]:
df=pd.concat([df1, df2], ignore_index=True)

In [11]:
df

,title,text,subject,date,f/t
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
44893,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
44894,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
44895,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
44896,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
44897,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [15]:
from nltk.stem import WordNetLemmatizer
import re
lemmatizer = WordNetLemmatizer()
corpus1=[]
for i in range(len(df)):
    review=re.sub('[^a-zA-Z5]',' ',df['title'][i])
    review= review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus1.append(review)

In [16]:
from nltk.stem import WordNetLemmatizer
import re
lemmatizer = WordNetLemmatizer()
corpus2=[]
for i in range(len(df)):
    review=re.sub('[^a-zA-Z5]',' ',df['text'][i])
    review= review.lower()
    review=review.split()
    review=[lemmatizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus2.append(review)

In [17]:
len(corpus1),len(corpus2)

(44898, 44898)

In [19]:
from nltk import sent_tokenize,word_tokenize

In [20]:
words1 = [word_tokenize(text) for text in corpus1]
words2 = [word_tokenize(text) for text in corpus2]
len(words1),len(words2)

(44898, 44898)

## Training Word2Vec model

In [17]:
import gensim
model=gensim.models.Word2Vec(words1+words2)

In [18]:
len(model.wv.index_to_key)

40292

In [19]:
model.wv.similar_by_word('trump')

[('obama', 0.6673877835273743),
 ('he', 0.5806102752685547),
 ('duterte', 0.5644303560256958),
 ('him', 0.5316070914268494),
 ('cruz', 0.5260862112045288),
 ('penny', 0.5223090648651123),
 ('putin', 0.5157760977745056),
 ('clinton', 0.5114418268203735),
 ('rubio', 0.511256754398346),
 ('abe', 0.5098899602890015)]

In [20]:
model.wv['trump'].shape

(100,)

In [21]:
len(model.wv.index_to_key)

40292

In [22]:
import numpy as np

In [23]:
def avgWord2Vec(doc):
    vectors=[model.wv[word] for word in doc  if word in model.wv.index_to_key]
    if(len(vectors)==0):
        return np.zeros(model.vector_size)
    return np.mean(vectors,axis=0)

In [24]:
from tqdm import tqdm
X1=[]
for i in tqdm(range(len(words1))):
    X1.append(avgWord2Vec(words1[i]))

100%|██████████| 44898/44898 [00:17<00:00, 2575.95it/s]

In [25]:
X2=[]
for i in tqdm(range(len(words2))):
    X2.append(avgWord2Vec(words2[i]))

100%|██████████| 44898/44898 [16:48<00:00, 44.53it/s]

In [27]:
len(X1)

44898

In [28]:
X1_new=np.array(X1)

In [138]:
X2_new=np.array(X2)

In [137]:
X1_new.shape

(44898, 100)

In [29]:
X = np.concatenate((X1, X2), axis=1) 
X.shape

(44898, 200)

In [30]:
y=df['f/t']

In [31]:
df_x=pd.DataFrame(X)

In [35]:
pd.concat([df_x,df['f/t']],axis=1).to_csv('output.csv')

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_x, y, test_size=0.2)

In [33]:
X_train

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
43869,0.722425,0.142330,-0.245942,0.612708,-1.484320,0.811638,0.293575,-0.487090,0.134301,-0.361040,...,-0.578191,0.103498,0.417473,-0.239980,-0.353439,0.668461,-0.187847,0.989873,-0.302323,-0.157745
27973,-1.254491,0.631180,0.041889,0.363677,0.519121,0.779205,0.108800,0.802354,0.008292,-0.146953,...,-1.070832,0.213200,0.330299,-0.793868,-0.692986,0.045941,0.193158,1.549165,-0.298852,-0.539036
42391,-0.725713,0.046146,0.390820,-0.198677,0.283577,0.095457,0.312294,0.516370,0.519855,-0.105082,...,-0.811436,0.016878,0.417309,-0.153778,-0.397892,0.635323,0.093578,0.886286,-0.302123,-0.361955
12268,0.211840,0.314656,0.208668,0.196923,-0.429212,0.278303,0.317186,-0.050523,0.624572,0.212817,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
40950,0.198800,-1.081291,-0.321142,1.647079,-0.399364,-0.262288,0.749837,-0.067598,0.466205,-0.492212,...,-0.530153,0.049154,0.566531,-0.382584,-0.714350,0.496739,-0.082277,0.994566,-0.441692,-0.032931
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17455,1.120485,-0.332374,-0.509442,0.357216,-1.031452,0.319048,0.942461,-1.076872,0.017917,0.188552,...,-0.641244,-0.101208,0.537293,-0.060698,-0.161388,0.753903,-0.376528,0.958901,-0.296738,-0.360034
12691,0.107458,-0.714010,-0.058267,-0.213519,-0.010974,0.323584,-0.105515,0.189922,-0.036413,0.002592,...,-0.286861,-0.494990,0.285298,-0.344689,0.510965,0.256155,0.190388,-0.274063,-0.160900,0.452186
13327,-0.299534,0.363167,0.610677,0.823539,-0.006397,0.481299,-0.176688,-0.253729,0.002805,-0.661037,...,-0.361273,0.009479,0.219712,0.221498,0.495682,0.672475,-0.604596,0.327482,0.183384,-0.549786
30335,0.647496,0.037892,0.168695,0.971270,-0.731036,0.294971,-0.189474,0.192894,0.650748,0.322561,...,-0.416614,0.330548,0.301131,-0.362862,-0.151642,0.551168,-0.050608,1.168658,-0.075872,-0.303140
29478,-0.505589,0.553417,0.852292,1.372803,0.654678,-0.818460,0.448903,-0.338032,0.480309,-0.263557,...,-0.597345,0.106041,0.474124,0.048646,-0.294934,0.182030,-0.070794,0.780780,-0.554880,-0.280589

In [1]:
import tensorflow as tf

In [2]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [14]:
## Build ANN model
model= Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

NameError: name 'X_train' is not defined

In [ ]:
model.summary()

In [ ]:
## defining the optimizers and loss function

opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()

In [ ]:
## compile the model

model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [ ]:
## Set up the tensorboard

log_dir="log/fit"+datetime.datetime.now().strftime("%y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [ ]:
## set up early stopping

ear_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
##Train the model

History=model.fit(
    X_train_scaled,y_train,validation_data=(X_test_scaled,y_test),
    epochs=100,
    callbacks=[tensorflow_callback,ear_stopping_callback]
    )