### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [4]:
import pandas as pd
d={
    'index':[1,2,3,4],
    'name':['barun','ram','sham','mohan'],
    'age':[21,29,32,24],
    'city':['delhi','haryana','gujrat','banglore']
}
df = pd.DataFrame(d,index=d['index'])
df

   index   name  age      city
1      1  barun   21     delhi
2      2    ram   29   haryana
3      3   sham   32    gujrat
4      4  mohan   24  banglore

In [12]:
import numpy as np 
df=pd.DataFrame(np.random.randint(1,100,size=(6,4)),columns=['A','B','C','D'])
df.set_index('A',inplace=True)
df

     B   C   D
A
98  60  68  74
86  25   7  45
87  36  97  89
34  49  14  71
37   2  74  37
29  66  29  68

In [18]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,3)),columns=['A','B','C'],index=['X','Y','Z'])
print(df)
print(df.at['Y','B'])

    A   B   C
X  11   8  72
Y  40  68  87
Z  17  26  84
68


### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [22]:
df=pd.DataFrame(np.random.randint(1,100,size=(5,3)))
df[3]=df[1]*df[2]
df

    0   1   2     3
0  76  33   1    33
1  37   7  56   392
2  26  67  54  3618
3  68  46  28  1288
4  86  80  29  2320

In [54]:
df=pd.DataFrame(np.random.randint(1,100,size=(4,3)))
print(df)
print(df.sum(axis=0))
print(df.sum(axis=1))

    0   1   2
0  21  59  47
1  28  74  56
2  16  49  68
3  76  74  91
0    141
1    256
2    262
dtype: int64
0    127
1    158
2    133
3    241
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [55]:
df=pd.DataFrame(np.random.randint(1,100,size=(5,3)))
df.at[1,2]=np.nan
print(df)
print(df.isnull().sum())
df[2]=df[2].fillna(df[2].mean())
df

    0   1     2
0  23   9  83.0
1  97  22   NaN
2  46  29  91.0
3  73  26  94.0
4  17  66  87.0
0    0
1    0
2    1
dtype: int64

    0   1      2
0  23   9  83.00
1  97  22  88.75
2  46  29  91.00
3  73  26  94.00
4  17  66  87.00

In [56]:
df=pd.DataFrame(np.random.randint(1,100,size=(5,3)))
df.at[1,2]=np.nan
print(df)
df.dropna(inplace=True) #it is used to delete the row with NaN value
print(df)
df[2]=df[2].astype(int) #converting the datatype into int of column 2
print(df)

    0   1     2
0  38  46  34.0
1  93  45   NaN
2  77  33  93.0
3   2  59  46.0
4  67  51  39.0
    0   1     2
0  38  46  34.0
2  77  33  93.0
3   2  59  46.0
4  67  51  39.0
    0   1   2
0  38  46  34
2  77  33  93
3   2  59  46
4  67  51  39


### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.