In [1]:
import pandas as pd

In [30]:
d={
    'name':['barun','ram','sham','mohan'],
    'age':[21,29,32,24],
    'city':['delhi','haryana','gujrat','banglore']
}
df=pd.DataFrame(d,index=['a','b','c','d'])
print(df['name'])
df.head(1)
df.tail(2)
df.loc['a']

a    barun
b      ram
c     sham
d    mohan
Name: name, dtype: object

name    barun
age        21
city    delhi
Name: a, dtype: object

In [31]:
import numpy as np
a=df['age'].sort_values()
a[-2]
b=pd.DataFrame(a)
b['age'][-1]=np.nan
b[-2:-1]
b
#df.head()[1:2]

/var/folders/_l/d3n9sd7d3y587cl59crr3lsc0000gn/T/ipykernel_83538/4051087240.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  a[-2]
/var/folders/_l/d3n9sd7d3y587cl59crr3lsc0000gn/T/ipykernel_83538/4051087240.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  b['age'][-1]=np.nan
/var/folders/_l/d3n9sd7d3y587cl59crr3lsc0000gn/T/ipykernel_83538/4051087240.py:5: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  b['age'][-1]=np.nan

    age
a  21.0
d  24.0
b  29.0
c   NaN

In [18]:
df1=pd.read_csv('Cleaned_Students_Performance.csv')
df1.head(5)
df1.shape[0]

1000

In [33]:
df.loc['a']
df['age'].value_counts()
a=df['age'].unique()
np.sort(a)

array([21, 24, 29, 32])

In [26]:
df1.loc[1]

gender                                    0
race_ethnicity                      group C
parental_level_of_education    some college
lunch                                     1
test_preparation_course                   1
math_score                               69
reading_score                            90
writing_score                            88
total_score                             247
average_score                     82.333333
Name: 1, dtype: object

In [7]:
d={
    'name':['barun','ram','sham','mohan'],
    'age':[21,29,32,24],
    'city':['delhi','haryana','gujrat','banglore']
}
df=pd.DataFrame(d,index=['a','b','c','d'])
print(df)
df['salary']=[100,200,300,140]
print(df)

    name  age      city
a  barun   21     delhi
b    ram   29   haryana
c   sham   32    gujrat
d  mohan   24  banglore
    name  age      city  salary
a  barun   21     delhi     100
b    ram   29   haryana     200
c   sham   32    gujrat     300
d  mohan   24  banglore     140

In [51]:
df.drop('salary',axis=1,inplace=True)

In [85]:
df.at['a',"age"]

np.int64(21)

In [64]:
df['age']=df['age']+1
df

    name  age      city
a  barun   23     delhi
b    ram   31   haryana
c   sham   34    gujrat
d  mohan   26  banglore

In [97]:
import numpy as np
df.at['a','age']=np.nan

In [98]:
df

    name   age      city  salary
a  barun   NaN     delhi     100
b    ram  29.0   haryana     200
c   sham  32.0    gujrat     300
d  mohan  24.0  banglore     140

In [101]:
df.isnull()

    name    age   city  salary
a  False   True  False   False
b  False  False  False   False
c  False  False  False   False
d  False  False  False   False

In [102]:
df.isnull().any()

name      False
age        True
city      False
salary    False
dtype: bool

In [103]:
df.isnull().sum()

name      0
age       1
city      0
salary    0
dtype: int64

In [118]:
df['age']=df['age'].fillna(df['age'].mean())
df

    name        age      city  salary   age_fill
a  barun  28.333333     delhi     100  28.333333
b    ram  29.000000   haryana     200  29.000000
c   sham  32.000000    gujrat     300  32.000000
d  mohan  24.000000  banglore     140  24.000000

In [6]:
df.size()

TypeError: 'int' object is not callable

In [19]:
import numpy as np

In [2]:
data = [[3, 'Brad', None, 4000], [1, 'John', 3, 1000], [2, 'Dan', 3, 2000], [4, 'Thomas', 3, 4000]]
employee = pd.DataFrame(data, columns=['empId', 'name', 'supervisor', 'salary']).astype({'empId':'Int64', 'name':'object', 'supervisor':'Int64', 'salary':'Int64'})
data = [[2, 500], [4, 2000]]
bonus = pd.DataFrame(data, columns=['empId', 'bonus']).astype({'empId':'Int64', 'bonus':'Int64'})

In [17]:
ans = pd.merge(employee,bonus,on='empId',how='left')
ans=pd.DataFrame(ans)
ans

   empId    name  supervisor  salary  bonus
0      3    Brad        <NA>    4000   <NA>
1      1    John           3    1000   <NA>
2      2     Dan           3    2000    500
3      4  Thomas           3    4000   2000

In [14]:
ans[ans['bonus']>1000]

   empId    name  supervisor  salary  bonus
3      4  Thomas           3    4000   2000

In [22]:
ans[(ans['bonus']<1000) | (ans['bonus']==<NA>)]

SyntaxError: invalid syntax (3946294387.py, line 1)

In [25]:
ans['name']

0      Brad
1      John
2       Dan
3    Thomas
Name: name, dtype: object